# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme_day: 1950s
theme_night: minimal
day_night: true
font: ''
font_size: L

# SEO

site_type: Person
description: I am a Ph.D. student at the Department of Statistics, Harvard University. I am interested in non parametric inference, high dimensional inference, statistical machine learning etc.
#twitter: 

# Contact (edit or remove options as required)

email: ritwikbhaduri@g.harvard.edu
phone: +1 8579997578
address:
  street: SC 316, Science center, 1 Oxford St
  city: Cambridge
  region: MA
  postcode: '02138'
  country: United States
  country_code: US
coordinates:
  latitude: '42.37593'
  longitude: '-71.117043'
#directions: 
#office_hours:
#appointment_url: 
#contact_links:

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: false
diagram: false
privacy_pack: false
#edit_page:
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: true
  share_alike: true
  allow_commercial: true
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: false
    project: true
    publication: true
    event: false
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
#marketing:
#  google_analytics: ''
#  google_tag_manager: ''
#  google_site_verification: ''
#  baidu_site_verification: ''
#  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: false
